### ISSUE TITLE
version of remote-booter

### ISSUE THREAD

**Issue by iaon** [xebialabs-community/gradle-xld-plugin#1]
Hi!

gradle-xld-plugin wants remote-booter:2014.10 but I see only 2014.7.4 /opt/xebia/xl-deploy/lib/local-booter-2014.7.4.jar  in my XLD installation. Google didn't help 
Do you have any suggestion how can I run this plugin?

Thanks!

**Comment by byaminov** [comment]
Hi Ivan!

Sorry, this plugin is currently work-in-progress, so the README is about "how it will work". I'll add that so that other people don't get confused.

We are currently in process of opening up several libraries needed by this plugin (and similar maven plugin), so when it's done - this project will become usable. And your comments will be welcome! This will probably happen in a couple of weeks.

**Comment by iaon** [comment]
Bulat,
Thanks for clarification. I'll look forward to updates :)

**Comment by byaminov** [comment]
@iaon: this plugin is now ready to use. Please follow the README and let me know if you find any issues!

**Comment by iaon** [comment]
Good news! Thank you!
